In [1]:
import numpy as np
import pandas as pd
import os
import pathlib
from dataset_loader import load_dataframes

df_list = [final_dt_df, final_w2v_df, final_nv_df, final_fin_df, final_in_df, final_se_df, all_df] = load_dataframes()

In [2]:
base_dir = f'{str(pathlib.Path().resolve())}/datasets'
atc_fname = 'DCDB_ATC codes.csv'
dn_fname = 'dcdb.csv'

path_atc = f'{base_dir}/{atc_fname}'
path_dname = f'{base_dir}/{dn_fname}'

atc_df = pd.read_csv(path_atc)
dn_df = pd.read_csv(path_dname)

drug_list = []
atc_list_1 = []
atc_list_2 = []
atc_list_3 = []
atc_dict = dict()

for i, row in enumerate(atc_df.values):
    drug = row[0]
    atc_codes = str(row[1]).replace('[', '').replace(']', '').replace("'", '').replace(' ', '').split(',')
    drug_list.append(drug)
    atc_list_1.append(atc_codes[0])
    if len(atc_codes) >= 2:
        atc_list_2.append(atc_codes[1])
    else:
        atc_list_2.append('-')
    if len(atc_codes) >= 3:
        atc_list_3.append(atc_codes[2])
    else:
        atc_list_3.append('-')
    atc_dict[drug] = i

a_list1 = []
a_list2 = []
a_list3 = []

for i, row in enumerate(dn_df.values):
    dcc = row[0]
    drug = row[1]
    if dcc in drug_list:
        inx = atc_dict[dcc]
        a_list1.append(atc_list_1[inx])
        a_list2.append(atc_list_2[inx])
        a_list3.append(atc_list_3[inx])
    else:
        a_list1.append('-')
        a_list2.append('-')
        a_list3.append('-')

dn_df['atc1'] = a_list1
dn_df['atc2'] = a_list2
dn_df['atc3'] = a_list3

dn_df.to_csv(f'{base_dir}/drug_atc.csv', index=False)

In [3]:
dn_df[dn_df['atc1'] == '-']

        drug         name atc1 atc2 atc3
3    DCC0639   Atrasentan    -    -    -
6    DCC0031   Butalbital    -    -    -
57   DCC0017    Carbidopa    -    -    -
69   DCC0532    Trientine    -    -    -
70   DCC0545   Sofosbuvir    -    -    -
..       ...          ...  ...  ...  ...
798  DCC0401      Phorbol    -    -    -
799  DCC0402      PD98059    -    -    -
815  DCC0190  Clavulanate    -    -    -
878  DCC0205       Sodium    -    -    -
880  DCC0207   Ethynodiol    -    -    -

[213 rows x 5 columns]

In [4]:
drugs_without_atc = dn_df[dn_df['atc1'] == '-']['name']
drugs_without_atc.to_csv(f'{base_dir}/drugs_without_atc2.csv', index=False)

In [5]:
drugs_with_atc_df = pd.read_csv(f'{base_dir}/drugs_without_atc.csv')
drugs_with_atc_df

            name     atc1 act2
0     Atrasentan        -    -
1     Butalbital  N05CB01    -
2      Carbidopa        -    -
3      Trientine  A16AX12    -
4     Sofosbuvir  J05AP08    -
..           ...      ...  ...
206   Perifosine        -    -
207       Taxane        -    -
208      Phorbol        -    -
209      PD98059        -    -
210  Clavulanate        -    -

[211 rows x 3 columns]

In [8]:
dn_df

        drug              name     atc1     atc2     atc3
0    DCC1838  Methyclothiazide  C03AA08        -        -
1    DCC0413       Garenoxacin  J01MA19        -        -
2    DCC0520           Betaine  A16AA06        -        -
3    DCC0639        Atrasentan        -        -        -
4    DCC0029        Lovastatin  C10AA02        -        -
..       ...               ...      ...      ...      ...
899  DCC0239        Salmeterol  R03AC12        -        -
900  DCC0148          Imatinib  L01XE01        -        -
901  DCC0149     Triamcinolone  A01AC01  D07AB09  D07XB02
902  DCC0150         Efavirenz  J05AG03        -        -
903  DCC0151        Bacitracin  D06AX05  R02AB04  J01XX10

[904 rows x 5 columns]

203

In [24]:
drug_atc_dict = dict()

for row in drugs_with_atc_df.values:
    drug = row[0]
    atc1 = row[1]
    atc2 = row[2]
    drug_atc_dict[drug] = [atc1, atc2]

atc1_list = []
atc2_list = []

for row in dn_df.values:
    drug = row[1]
    atc1 = row[2]
    atc2 = row[3]
    if atc1 == '-':
        if drug in list(drug_atc_dict.keys()):
            atc1_list.append(drug_atc_dict[drug][0])
            atc2_list.append(drug_atc_dict[drug][1])
        else:
            atc1_list.append(atc1)
            atc2_list.append(atc2)
    else:
        atc1_list.append(atc1)
        atc2_list.append(atc2)

dn_df['atc1'] = atc1_list
dn_df['atc2'] = atc2_list

In [28]:
code_dict = dict()
code_dict['A'] = 'Alimentary tract and metabolism'
code_dict['B'] = 'Blood and blood forming organs'
code_dict['C'] = 'Cardiovascular system'
code_dict['D'] = 'Dermatologicals'
code_dict['G'] = 'Genito-urinary system and sex hormones'
code_dict['H'] = 'Systemic hormonal preparations, excluding sex hormones and insulins'
code_dict['J'] = 'Antiinfectives for systemic use'
code_dict['L'] = 'Antineoplastic and immunomodulating agents'
code_dict['M'] = 'Musculo-skeletal system'
code_dict['N'] = 'Nervous system'
code_dict['P'] = 'Antiparasitic products, insecticides and repellents'
code_dict['R'] = 'Respiratory system'
code_dict['S'] = 'Sensory organs'
code_dict['V'] = 'Various'
code_dict

{'A': 'Alimentary tract and metabolism',
 'B': 'Blood and blood forming organs',
 'C': 'Cardiovascular system',
 'D': 'Dermatologicals',
 'G': 'Genito-urinary system and sex hormones',
 'H': 'Systemic hormonal preparations, excluding sex hormones and insulins',
 'J': 'Antiinfectives for systemic use',
 'L': 'Antineoplastic and immunomodulating agents',
 'M': 'Musculo-skeletal system',
 'N': 'Nervous system',
 'P': 'Antiparasitic products, insecticides and repellents',
 'R': 'Respiratory system',
 'S': 'Sensory organs',
 'V': 'Various'}

In [45]:
atc1_first_list = []
atc2_first_list = []
atc1_class_list = []
atc2_class_list = []

for row in dn_df.values:
    dcc = row[0]
    drug = row[1]
    atc1 = row[2]
    atc2 = row[3]
    if atc1 == '-':
        atc1_first_list.append('-')
        atc2_first_list.append('-')
        atc1_class_list.append('-')
        atc2_class_list.append('-')
    else:
        atc1_first_list.append(str(atc1)[0])
        if str(atc1)[0] in list(code_dict.keys()):
            atc1_class_list.append(code_dict[str(atc1)[0]])
        else:
            atc1_class_list.append('-')
        if atc2 != '-':
            atc2_first_list.append(str(atc2)[0])
            if str(atc2)[0] in list(code_dict.keys()):
                atc2_class_list.append(code_dict[str(atc2)[0]])
            else:
                atc2_class_list.append('-')
        else:
            atc2_first_list.append('-')
            atc2_class_list.append('-')

dn_df['atc1_first'] = atc1_first_list
dn_df['atc2_first'] = atc2_first_list
dn_df['atc1_first_class'] = atc1_class_list
dn_df['atc2_first_class'] = atc2_class_list

In [47]:
dn_df.to_csv(f'{base_dir}/dcdb_atc.csv')
dn_df

,drug,name,atc1,atc2,atc3,atc1_first,atc2_first,atc1_first_class,atc2_first_class
0,DCC1838,Methyclothiazide,C03AA08,-,-,C,-,Cardiovascular system,-
1,DCC0413,Garenoxacin,J01MA19,-,-,J,-,Antiinfectives for systemic use,-
2,DCC0520,Betaine,A16AA06,-,-,A,-,Alimentary tract and metabolism,-
3,DCC0639,Atrasentan,-,-,-,-,-,-,-
4,DCC0029,Lovastatin,C10AA02,-,-,C,-,Cardiovascular system,-
...,...,...,...,...,...,...,...,...,...
899,DCC0239,Salmeterol,R03AC12,-,-,R,-,Respiratory system,-
900,DCC0148,Imatinib,L01XE01,-,-,L,-,Antineoplastic and immunomodulating agents,-
901,DCC0149,Triamcinolone,A01AC01,D07AB09,D07XB02,A,D,Alimentary tract and metabolism,Dermatologicals
902,DCC0150,Efavirenz,J05AG03,-,-,J,-,Antiinfectives for systemic use,-
903,DCC0151,Bacitracin,D06AX05,R02AB04,J01XX10,D,R,Dermatologicals,Respiratory system

# Adding ATC codes of drug combinations

In [61]:
base_path = f'{str(pathlib.Path().resolve())}'

all_new_edges_df = pd.read_csv(f'{base_path}/new_edges/new_ddc_unique.csv')

drug_atc_dict = dict()

for row in dn_df.values:
    drug = row[1]
    atc = row[2]
    atc_first = row[5]
    drug_atc_dict[drug] = [atc, atc_first]

d1_atc_list = []
d2_atc_list = []

d1_atc_first_list = []
d2_atc_first_list = []

for row in all_new_edges_df.values:
    d1 = row[0]
    d2 = row[1]
    d1_atc_list.append(drug_atc_dict[d1][0])
    d2_atc_list.append(drug_atc_dict[d2][0])
    d1_atc_first_list.append(drug_atc_dict[d1][1])
    d2_atc_first_list.append(drug_atc_dict[d2][1])

all_new_edges_df['atc1'] = d1_atc_list
all_new_edges_df['atc2'] = d2_atc_list

all_new_edges_df['atc1_first'] = d1_atc_first_list
all_new_edges_df['atc2_first'] = d2_atc_first_list

all_new_edges_df.to_csv(f'{base_path}/new_edges/new_ddc_unique_with_atc.csv', index=False)
all_new_edges_df

               d1           d2  count     atc1     atc2 atc1_first atc2_first
0      Lamivudine  Delavirdine      8  J05AF05  J05AG02          J          J
1      Lamivudine  Rifapentine      8  J05AF05  J04AB05          J          J
2      Lamivudine    Indinavir      7  J05AF05  J05AE02          J          J
3      Lamivudine    Darunavir      7  J05AF05  J05AE10          J          J
4      Lamivudine    Rifabutin      6  J05AF05  J04AB04          J          J
..            ...          ...    ...      ...      ...        ...        ...
639      Valproic   Carmustine      1  N03AG01  L01AD01          N          L
640       Aspirin   Furosemide      1  A01AD05  C03CA01          A          C
641       Aspirin   Ketoprofen      1  A01AD05  M01AE03          A          M
642       Aspirin   Ergotamine      1  A01AD05  N02CA01          A          N
643  Elvitegravir   Didanosine      1  J05AX11  J05AF02          J          J

[644 rows x 7 columns]